### ISSUE TITLE
tests fail if festvox.org is down

### ISSUE THREAD

**Issue by psibre** [marytts/gradle-marytts-voicebuilding-plugin#62]
Right now,
```
$ ping festvox.org
ping: cannot resolve festvox.org: Unknown host
```
Therefore the tiny limited domain database used as a test dependency cannot be resolved, and obviously
```
Gradle suite > Gradle test > de.dfki.mary.voicebuilding.BuildLogicFunctionalTest.testGenerateAllophones FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /Users/ingmar/workspace/gradle-marytts-voicebuilding-plugin/data-plugin/build/testProject with arguments [generateAllophones]

    Output:
    :generateSource UP-TO-DATE
    :compileMaryttsJava UP-TO-DATE
    :compileMaryttsGroovy UP-TO-DATE
    :processMaryttsResources UP-TO-DATE
    :maryttsClasses UP-TO-DATE
    :processDataResources
    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not resolve all dependencies for configuration ':data'.
    > Could not resolve org.festvox:cmu_time_awb:.
      Required by:
          :testProject:unspecified
       > Could not resolve org.festvox:cmu_time_awb:.
          > Could not get resource 'http://festvox.org/examples/cmu_time_awb_[classifier]/packed/ivy.xml'.
             > Could not GET 'http://festvox.org/examples/cmu_time_awb_%5Bclassifier%5D/packed/ivy.xml'.
                > festvox.org: unknown error

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


    BUILD FAILED

    Total time: 4.651 secs
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:213)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:210)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:273)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:210)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$build$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at de.dfki.mary.voicebuilding.BuildLogicFunctionalTest.testGenerateAllophones(BuildLogicFunctionalTest.groovy:221)
```

**Comment by psibre** [comment]
It seems festvox.org is back up, but to make matters more robust for the future, I've deployed the required file as [a new package in our Bintray repo](https://bintray.com/marytts/marytts/festvox-examples).
